// react-task-manager/src/components/TaskList.jsx
import React from 'react';

function TaskList({ tasks, deleteTask, toggleComplete }) {
  return (
    <ul>
      {tasks.map((task) => (
        <li key={task.id} className={task.completed ? 'completed' : ''}>
          <input
            type="checkbox"
            checked={task.completed}
            onChange={() => toggleComplete(task.id)}
          />
          {task.title} - Priority: {task.priority}
          <button onClick={() => deleteTask(task.id)}>Delete</button>
        </li>
      ))}
    </ul>
  );
}

export default TaskList;

// vue-task-manager/src/components/TaskList.vue
<template>
  <ul>
    <li v-for="task in tasks" :key="task.id" :class="{ completed: task.completed }">
      <input type="checkbox" :checked="task.completed" @change="toggleComplete(task.id)" />
      {{ task.title }} - Priority: {{ task.priority }}
      <button @click="deleteTask(task.id)">Delete</button>
    </li>
  </ul>
</template>

<script>
export default {
  props: {
    tasks: {
      type: Array,
      required: true,
    },
  },
  emits: ['deleteTask', 'toggleComplete'],
  methods: {
    deleteTask(taskId) {
      this.$emit('deleteTask', taskId);
    },
    toggleComplete(taskId) {
      this.$emit('toggleComplete', taskId);
    },
  },
};
</script>

<style scoped>
/* Styles for TaskList component */
</style>
