// vue-task-manager/src/App.vue
<template>
  <div class="app">
    <h1>Vue Task Manager</h1>
    <TaskForm @addTask="addTask" />
    <div>
      <label for="priorityFilter">Filter by Priority:</label>
      <select id="priorityFilter" v-model="filterPriority">
        <option value="all">All</option>
        <option value="high">High</option>
        <option value="medium">Medium</option>
        <option value="low">Low</option>
      </select>
    </div>
    <TaskList :tasks="filteredTasks" @deleteTask="deleteTask" @toggleComplete="toggleComplete" />
  </div>
</template>

<script>
import TaskList from './components/TaskList.vue';
import TaskForm from './components/TaskForm.vue';

export default {
  components: {
    TaskList,
    TaskForm,
  },
  data() {
    return {
      tasks: [],
      filterPriority: 'all',
    };
  },
  mounted() {
    const storedTasks = localStorage.getItem('tasks');
    if (storedTasks) {
      this.tasks = JSON.parse(storedTasks);
    }
  },
  watch: {
    tasks: {
      handler(newTasks) {
        localStorage.setItem('tasks', JSON.stringify(newTasks));
      },
      deep: true,
    },
  },
  computed: {
    filteredTasks() {
      if (this.filterPriority === 'all') {
        return this.tasks;
      }
      return this.tasks.filter((task) => task.priority === this.filterPriority);
    },
  },
  methods: {
    addTask(newTask) {
      this.tasks.push(newTask);
    },
    deleteTask(taskId) {
      this.tasks = this.tasks.filter((task) => task.id !== taskId);
    },
    toggleComplete(taskId) {
      this.tasks = this.tasks.map((task) =>
        task.id === taskId ? { ...task, completed: !task.completed } : task
      );
    },
  },
};
</script>

<style scoped>
.app {
  font-family: sans-serif;
  text-align: center;
}

ul {
  list-style: none;
  padding: 0;
}

li {
  padding: 8px;
  border-bottom: 1px solid #eee;
}

.completed {
  text-decoration: line-through;
  color: #888;
}
</style>

// react-task-manager/src/App.jsx
import React, { useState, useEffect } from 'react';
import TaskList from './components/TaskList';
import TaskForm from './components/TaskForm';
import './App.css';

function App() {
  const [tasks, setTasks] = useState([]);
  const [filterPriority, setFilterPriority] = useState('all');

  useEffect(() => {
    const storedTasks = localStorage.getItem('tasks');
    if (storedTasks) {
      setTasks(JSON.parse(storedTasks));
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('tasks', JSON.stringify(tasks));
  }, [tasks]);

  const addTask = (newTask) => {
    setTasks([...tasks, newTask]);
  };

  const deleteTask = (taskId) => {
    setTasks(tasks.filter((task) => task.id !== taskId));
  };

  const toggleComplete = (taskId) => {
    setTasks(tasks.map((task) =>
      task.id === taskId ? { ...task, completed: !task.completed } : task
    ));
  };

  const filteredTasks = filterPriority === 'all'
    ? tasks
    : tasks.filter(task => task.priority === filterPriority);

  return (
    <div className="app">
      <h1>React Task Manager</h1>
      <TaskForm addTask={addTask} />
      <div>
        <label htmlFor="priorityFilter">Filter by Priority:</label>
        <select
          id="priorityFilter"
          value={filterPriority}
          onChange={(e) => setFilterPriority(e.target.value)}
        >
          <option value="all">All</option>
          <option value="high">High</option>
          <option value="medium">Medium</option>
          <option value="low">Low</option>
        </select>
      </div>
      <TaskList tasks={filteredTasks} deleteTask={deleteTask} toggleComplete={toggleComplete} />
    </div>
  );
}

export default App;
