// vue-task-manager/src/components/TaskForm.vue
<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" placeholder="Task title" v-model="title" />
    <select v-model="priority">
      <option value="high">High</option>
      <option value="medium">Medium</option>
      <option value="low">Low</option>
    </select>
    <button type="submit">Add Task</button>
  </form>
</template>

<script>
export default {
  data() {
    return {
      title: '',
      priority: 'medium',
    };
  },
  emits: ['addTask'],
  methods: {
    handleSubmit() {
      if (this.title.trim() !== '') {
        this.$emit('addTask', {
          id: Date.now(),
          title: this.title,
          completed: false,
          priority: this.priority,
        });
        this.title = '';
      }
    },
  },
};
</script>

<style scoped>
/* Styles for TaskForm component */
</style>

// react-task-manager/src/components/TaskForm.jsx
import React, { useState } from 'react';

function TaskForm({ addTask }) {
  const [title, setTitle] = useState('');
  const [priority, setPriority] = useState('medium');

  const handleSubmit = (e) => {
    e.preventDefault();
    if (title.trim() !== '') {
      addTask({
        id: Date.now(),
        title: title,
        completed: false,
        priority: priority
      });
      setTitle('');
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="text"
        placeholder="Task title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <select value={priority} onChange={(e) => setPriority(e.target.value)}>
        <option value="high">High</option>
        <option value="medium">Medium</option>
        <option value="low">Low</option>
      </select>
      <button type="submit">Add Task</button>
    </form>
  );
}

export default TaskForm;
